# Generated by Django 3.1.7 on 2021-03-24 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('sname', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('pw', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crews', to='musical_chairs.captain')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=20)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='musical_chairs.captain')),
                ('crew_status', models.ManyToManyField(to='musical_chairs.Crew')),
            ],
        ),
    ]
