# Generated by Django 3.1.7 on 2021-04-23 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musical_chairs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='crew_status',
        ),
        migrations.AlterField(
            model_name='crew',
            name='captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='captains', to='musical_chairs.captain'),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('...', '...'), ('Training', 'Training'), (
                    'Novice', 'Novice'), ('Master', 'Master')], default='Training', max_length=100)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='captain', to='musical_chairs.captain')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='crewStatus', to='musical_chairs.crew')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='tasker', to='musical_chairs.task')),
            ],
        ),
    ]
