# Generated by Django 3.1.7 on 2021-04-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musical_chairs', '0002_auto_20210423_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('...', 'Unexperienced'), ('Training', 'Training'), ('Novice', 'Novice'), ('Master', 'Master')], default='...', max_length=100),
        ),
    ]
