# Generated by Django 3.1.7 on 2021-08-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musical_chairs', '0003_auto_20210423_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='skills',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('...', '...'), ('Training', 'Training'), ('Novice', 'Novice'), ('Master', 'Master'), ('Restricted', 'Restricted')], default='...', max_length=100),
        ),
    ]
